In [1]:
# make sure it is done before starting to train
!cd .. && python setup.py install && pip install pytorch_lightning==1.5

running install
/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based t

In [1]:
from run import main

%load_ext autoreload
%autoreload 2

2024-09-01 16:11:52.069178: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [ ]:
main()

/home/vlsta001/git_projects/ncps-slaf/slaf-project/run.py:25: DtypeWarning: Columns (15,16,17,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/configuration_validator.py:118: UserWarning: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
  rank_zero_warn("You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [1]

  | Name  | Type | Params
-------------------------------
0 | model | LTC  | 2.1 K 
-------------------------------
1.7 K     Trainable params
416       Non-trainable params
2.1 K     Total params
0.009     Total estimated model params size (MB)
/opt/conda/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:617: UserWarning: Che

Training: 0it [00:00, ?it/s]

In [31]:
x_features = x_features.view(1, -1, 12).to("cuda")

In [7]:
with torch.no_grad():
    prediction = ltc_model(x_features)[0].cpu().numpy()

NameError: name 'ltc_model' is not defined

In [5]:
import torch
torch.cuda.empty_cache()

In [6]:
import pytorch_lightning as pl
from src.model import SequenceLearner
from ncps.torch import LTC

In [22]:
ltc_model.rnn_cell._params

{'gleak': Parameter containing:
 tensor([ 0.5486,  0.4239,  0.1719, -0.0120,  0.6637,  0.4144,  0.4927,  0.6642,
          0.0920,  0.5700,  1.1297,  0.2036,  0.3742,  0.6899, -0.0373, -0.0927],
        device='cuda:0', requires_grad=True),
 'vleak': Parameter containing:
 tensor([-0.1259,  0.0777,  0.1339, -0.0810, -0.1015,  0.1676, -0.0340, -0.4740,
          0.1738, -0.0851, -0.3193,  0.4339, -0.0191, -0.0515,  0.2666,  0.2213],
        device='cuda:0', requires_grad=True),
 'cm': Parameter containing:
 tensor([ 0.3133,  0.2851,  0.3259,  0.2862,  0.6695,  0.5799,  0.3181,  0.5945,
          0.0079,  0.0712,  0.7853,  0.1556,  0.2836,  0.6392, -0.5176,  0.3765],
        device='cuda:0', requires_grad=True),
 'sigma': Parameter containing:
 tensor([[5.8680, 6.7454, 6.7089, 5.7572, 3.1925, 7.9168, 4.7443, 6.8359, 5.6683,
          6.7878, 5.2758, 3.0416, 3.8133, 6.9963, 7.1448, 4.6257],
         [7.0227, 3.7600, 3.5156, 4.9956, 5.5837, 6.2822, 7.1935, 7.0405, 7.5923,
          5.1347,

In [32]:
model = SequenceLearner.load_from_checkpoint("/home/vlsta001/git_projects/ncps-slaf/slaf-project/checkpoints/epoch=0-step=311-v14.ckpt")
model.model.to("cuda")
model.model.eval()

LTC(
  (rnn_cell): LTCCell(
    (make_positive_fn): Softplus(beta=1, threshold=20)
    (_clip): ReLU()
  )
)

In [33]:
x_features

tensor([[[0.2900, 0.2262, 0.2055,  ..., 1.0000, 0.0000, 0.0000],
         [0.2594, 0.1932, 0.1697,  ..., 0.0000, 0.0000, 0.0000],
         [0.2398, 0.1805, 0.1433,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.5665, 0.3527, 0.4628,  ..., 0.0000, 0.0000, 0.0000],
         [0.5246, 0.3314, 0.4441,  ..., 0.0000, 0.0000, 0.0000],
         [0.4662, 0.3093, 0.3949,  ..., 0.0000, 0.0000, 0.0000]]],
       device='cuda:0')

In [34]:
# predict with the model
y_hat = model.model(x_features)

In [35]:
y_hat

(tensor([[[0.2006],
          [0.3179],
          [0.3485],
          [0.3368],
          [0.3201],
          [0.3162],
          [0.3363],
          [0.3957],
          [0.4668],
          [0.5157],
          [0.5344],
          [0.5338],
          [0.5278],
          [0.5155],
          [0.4922],
          [0.4679],
          [0.4582],
          [0.4750],
          [0.5078],
          [0.5271],
          [0.5344],
          [0.5348],
          [0.5264],
          [0.5041],
          [0.4795],
          [0.4660],
          [0.4463],
          [0.4388],
          [0.4573],
          [0.5038],
          [0.5604],
          [0.6024],
          [0.6313],
          [0.6532],
          [0.6687],
          [0.6774],
          [0.6802],
          [0.6794],
          [0.6774],
          [0.6756],
          [0.6761],
          [0.6817],
          [0.6905],
          [0.6969],
          [0.6987],
          [0.6963],
          [0.6893],
          [0.6766],
          [0.6595],
          [0.6444],
